/**
 * DGGS 1.0 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.19-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DapaExternalDocs } from './dapaExternalDocs';
import { Link } from './link';


export interface DapaEndpoints { 
    mediaTypes?: Array<string>;
    externalDocs?: DapaExternalDocs;
    inputCollectionId: string;
    id: string;
    title?: string;
    links?: Array<Link>;
    description?: string;
}

