/**
 * DGGS 1.0 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.19-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MultipolygonGeoJSON { 
    type: MultipolygonGeoJSON.TypeEnum;
    coordinates: Array<Array<Array<Array<number>>>>;
}
export namespace MultipolygonGeoJSON {
    export type TypeEnum = 'MultiPolygon';
    export const TypeEnum = {
        MultiPolygon: 'MultiPolygon' as TypeEnum
    };
}


