/**
 * DGGS 1.0 server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.19-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MultilinestringGeoJSON { 
    type: MultilinestringGeoJSON.TypeEnum;
    coordinates: Array<Array<Array<number>>>;
}
export namespace MultilinestringGeoJSON {
    export type TypeEnum = 'MultiLineString';
    export const TypeEnum = {
        MultiLineString: 'MultiLineString' as TypeEnum
    };
}


